version: '3.8'

services:
  graphrag-chat:
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - STREAMLIT_PORT=8501
      - STREAMLIT_HOST=0.0.0.0
    volumes:
      - ../../data:/app/data
      - ../../config:/app/config
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped
    networks:
      - graphrag-network

networks:
  graphrag-network:
    driver: bridge